### ISSUE TITLE
TypeError: Cannot read property 'compile' of undefined

### ISSUE THREAD

**Issue by tufu9441** [hexojs/hexo-renderer-jade#4]
After updating Hexo to 3.2.0 and hexo-renderer-jade to 0.3.0, following errors occur when `hexo g`:

![screencapture at sun feb 28 20 59 52 cst 2016](https://cloud.githubusercontent.com/assets/6790361/13379353/43eefb62-de5e-11e5-85b5-9b0679b1f5e5.png)
![screencapture at sun feb 28 21 01 57 cst 2016](https://cloud.githubusercontent.com/assets/6790361/13379375/9b560972-de5e-11e5-943e-ca06eaf841c6.png)
![screencapture at sun feb 28 21 02 13 cst 2016](https://cloud.githubusercontent.com/assets/6790361/13379377/a2b2b076-de5e-11e5-980a-26a33ba2be1b.png)

**Comment by tommy351** [comment]
What theme are you using?

**Comment by tufu9441** [comment]
[Maupassant](https://github.com/tufu9441/maupassant-hexo)

**Comment by tommy351** [comment]
I tested on a new folder and it works. Maybe you can try to remove `node_modules` and run `npm install` again.

<img width="596" alt="2016-02-28 22 15 55" src="https://cloud.githubusercontent.com/assets/411425/13379733/dc9756e8-de68-11e5-9bda-ab0dfed3a17f.PNG">

**Comment by tufu9441** [comment]
I tried but failed again. Is it possible that it is related with the version of Node? What's the version of Node you use?

**Comment by tommy351** [comment]
```
hexo: 3.2.0
hexo-cli: 1.0.1
os: Darwin 15.4.0 darwin x64
http_parser: 2.5.1
node: 4.3.0
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2f
```

**Comment by tufu9441** [comment]
Can you succeed to `hexo s` and visit the normal pages?

**Comment by tommy351** [comment]
Yes. Not a problem.

**Comment by tufu9441** [comment]
That is so strange, I tried to `hexo init` several folders to test, but failed all.

**Comment by tufu9441** [comment]
My present hexo version is:
```
hexo: 3.2.0
hexo-cli: 1.0.1
os: Darwin 15.3.0 darwin x64
http_parser: 2.5.1
node: 4.3.0
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2f
```
and the same problem keeps happening.

I have to use Hexo 3.1.1 again and it can work normally at least. :(

**Comment by tommy351** [comment]
Maybe there's something wrong with your `_config.yml`? Could you post the `_config.yml` if you don't mind?

**Comment by tufu9441** [comment]
```YAML
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 屠城
subtitle: 屠夫9441的博客
description: 屠城 | 屠夫9441 | 独立博客 | Hexo | Typecho | Wordpress | 心情 | 随笔
author: 屠夫9441
language: zh-CN
timezone: Asia/Taipei

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.haomwei.com
root: /
permalink: :category/:title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
about_dir: about/
history_dir: history/
archive_dir: archives/
guestbook_dir: guestbook/
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  auto_detect: true
  line_number: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:
  主机: host
  五道口: wudaokou
  体育: sports
  博客: blog
  吃: eat
  多说: duoshuo
  心情: emotion
  技术: technology
  李杨: jeffery
  棒球英豪: touch
  空间: space
  随笔: manuscript
  音乐: music
  电影: movie

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY年MM月DD日
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: maupassant

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo:
     github: git@github.com:tufu9441/hexo-blog.git,master

plugins:
  - hexo-generator-sitemap
  - hexo-generator-baidu-sitemap

baidusitemap:
    path: baidusitemap.xml


archive_generator:
    per_page: 0 ##归档页面默认10篇文章标题
    yearly: true  ##生成年视图
    monthly: false ##生成月视图

tag_generator:
    per_page: 1000 ##标签分类页面默认10篇文章

category_generator:
    per_page: 1000 ###分类页面默认10篇文章
```

**Comment by tufu9441** [comment]
And the `_config.yml` of the theme:
```YAML
fancybox: true
duoshuo:
disqus: haomwei
google_search: true
baidu_search: false
swiftype:
tinysou:
google_analytics: ## Your Google Analytics tracking id, e.g. UA-XXXXXX-X
baidu_analytics:
shareto: true
busuanzi: true
menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user
  - page: history
    directory: history/
    icon: fa-book
  - page: guestbook
    directory: guestbook/
    icon: fa-comments
  - page: rss
    directory: atom.xml
    icon: fa-rss

widgets:
  - search
  - category
  - tag
  - recent_posts
  - recent_comments
  - links

links:
  - title: 雅岚文艺博客
    url: http://www.yalanbooks.net/
  - title: 羽中漫步
    url: http://www.jzwalk.com/
  - title: 灰常记忆
    url: http://bestcherish.com/
  - title: 怡红院落
    url: http://imnerd.org/
  - title: 生活志
    url: http://louishan.com/
  - title: 葛豪武
    url: https://www.gehaowu.com/
  - title: 浩子
    url: http://haozer.com
  - title: James Pan's Blog
    url: http://blog.jamespan.me

# Static files
css: css
js: js

# Theme version
version: 1.1.7
```
